# Generated by Django 3.1.4 on 2020-12-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_language',
            field=models.CharField(max_length=50),
        ),
    ]
