# Generated by Django 3.1.4 on 2020-12-30 06:47

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(db_column='First Name Test', max_length=40)),
                ('Last_Name', models.CharField(db_column='Last Name', max_length=40)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
    ]
