# Generated by Django 3.1.4 on 2021-01-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='Age',
            field=models.IntegerField(help_text='Bvc enter proper Age'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
