# Generated by Django 3.1.4 on 2021-01-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0002_auto_20210102_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBooks',
            fields=[
                ('B_ID', models.AutoField(db_column='Book ID', primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(db_column='Book Name', max_length=40)),
                ('Book_Type', models.CharField(choices=[(1, 'Poetry'), (2, 'Philosopy')], max_length=10)),
            ],
        ),
    ]
