# Generated by Django 3.1.4 on 2021-01-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0005_auto_20210102_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooks',
            name='Book_Type',
            field=models.CharField(choices=[('poet', 'Poetry'), ('Philo', 'Philosopy')], max_length=10),
        ),
    ]
