# Generated by Django 3.1.4 on 2021-01-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForms', '0006_auto_20210103_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooks',
            name='Book_Type',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=10),
        ),
    ]
